### ISSUE TITLE
Provide null safety for compatibility with latest version of flutter

### ISSUE THREAD

**Issue by fsol11** [tekartik/common_utils.dart#16]
As a developer I need this library to be null safe so that it works with Flutter 2.12.0 and later.

**Comment by alextekartik** [comment]
Unfortunately with git dependencies it is not always possible to target both pre-nnbd and nnbd. The choice I made was to create a null_safety branch while the dart2 branch is for pre-nnbd.

So the solution is to import it this way:

```yaml
dependencies:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: null_safety
```
